name: Pipeline CI/CD - PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Iniciando build e deploy
    runs on:ubuntu-latest
    environments:production